Automatic columns selector for joins function
scicloj/tablecloth pull request #168
Opened 2024-09-02 07:15 UTC by pcbldi

This changes introduces an automatic column selector as discussed in #133 .

All the common columns in two datasets are used as the column selectors.

2024-09-03 11:27 UTC, genmeblog reviewed
You don't have to change `api.clj` file since it's generated. https://github.com/scicloj/tablecloth/blob/master/src/tablecloth/api/api_template.clj#L182

2024-09-03 11:28 UTC, genmeblog requested changes

2024-09-03 11:28 UTC, genmeblog commented on src/tablecloth/api/join_concat_ds.clj
> +   (let [cols-l (set (column-names ds-left :all))
`:all` can be skipped.

2024-09-03 11:28 UTC, genmeblog commented on src/tablecloth/api/join_concat_ds.clj
> +         cols-r (set (column-names ds-right :all))]
`:all` can be skipped.

2024-09-16 20:42 UTC, prakash-defnx commented
> You don't have to change `api.clj` file since it's generated. https://github.com/scicloj/tablecloth/blob/master/src/tablecloth/api/api_template.clj#L182

thanks, should I revert the changes in that ns completely? or its ok to leave what changes are there?

2024-09-16 20:43 UTC, prakash-defnx commented on src/tablecloth/api/join_concat_ds.clj
> +   (let [cols-l (set (column-names ds-left :all))
done,thanks.

2024-09-16 20:43 UTC, prakash-defnx commented on src/tablecloth/api/join_concat_ds.clj
> +         cols-r (set (column-names ds-right :all))]
done, thanks

2025-02-09 17:13 UTC, behrica commented
very useful, I was thinking about requesting this as well,as such common case.

2026-08-02 21:11 UTC, genmeblog approved these changes

2026-08-02 21:11 UTC, merged